name: Brex Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libboost-all-dev
    - name: Install
      run: make -f ./build/makefile all
    - name: Run Tests
      run: make -f ./build/makefile test
